### ISSUE TITLE
Can't compile actix-cors 

### ISSUE THREAD

**Issue by sergiupopescu199** [actix/actix-extras#173] opened 2021-04-01 17:18 UTC
Hi, I wanted to use actix-cors, I had some issues using the version 0.5.4 on actix-web 4.0.0.beta.4, I started compiling actix-cors and it says that:

```rust
Checking actix-http v3.0.0-beta.4
error[E0432]: unresolved import `actix_utils::timeout`
  --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/client/connector.rs:17:18
   |
17 | use actix_utils::timeout::{TimeoutError, TimeoutService};
   |                  ^^^^^^^ could not find `timeout` in `actix_utils`

error[E0432]: unresolved import `actix_utils::dispatcher`
  --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/error.rs:10:18
   |
10 | use actix_utils::dispatcher::DispatcherError as FramedDispatcherError;
   |                  ^^^^^^^^^^ could not find `dispatcher` in `actix_utils`

error[E0432]: unresolved import `actix_utils::timeout`
  --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/error.rs:11:18
   |
11 | use actix_utils::timeout::TimeoutError;
   |                  ^^^^^^^ could not find `timeout` in `actix_utils`

error[E0432]: unresolved import `actix_utils::dispatcher`
 --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/ws/dispatcher.rs:7:18
  |
7 | use actix_utils::dispatcher::{Dispatcher as InnerDispatcher, DispatcherError};
  |                  ^^^^^^^^^^ could not find `dispatcher` in `actix_utils`

error[E0392]: parameter `S` is never used
  --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/ws/dispatcher.rs:12:23
   |
12 | pub struct Dispatcher<S, T>
   |                       ^ unused parameter
   |
   = help: consider removing `S`, referring to it in a field, or using a marker such as `PhantomData`

error[E0392]: parameter `T` is never used
  --> /home/sergiu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.4/src/ws/dispatcher.rs:12:26
   |
12 | pub struct Dispatcher<S, T>
   |                          ^ unused parameter
   |
   = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`

error: aborting due to 6 previous errors
```
- rust version  rustc 1.51.0 (2fd73fabe 2021-03-23)

I want to use cors with actix-web 4.0.0.beta4, I tried with version 3 but I need tokio version 1.

**Comment by JohnTitor** [comment] 2021-04-01 18:50
Duplicate of #171.
Cors 0.5.4 has no compatibility with actix-web 4 (beta).

**Closed by JohnTitor** 2021-04-01 18:50 UTC

**Comment by robjtede** [comment] 2021-04-02 11:08
cors 0.6.0-beta.1 released
