### ISSUE TITLE
actix-session's purge() function does not apply (nor does remove()) when done in an HTTP Post request

### ISSUE THREAD

**Issue by john01dav** [actix/actix-extras#158] opened 2021-02-18 03:18 UTC
## Expected Behavior & Current Behavior
I'm using actix session for accounts, but in my sign out route when I call either [purge](https://docs.rs/actix-session/0.4.0/actix_session/struct.Session.html#method.purge) or [remove](https://docs.rs/actix-session/0.4.0/actix_session/struct.Session.html#method.remove), although a proper set-cookie header is sent, both Firefox and Midori (which is based on Webkit, which is entirely separate from Firefox) ignore it and keep the old session set and the user signed in.

## Possible Solution
I have no idea why Firefox and Midori (probably every other browser too) are ignoring the set-cookie header, but in the meantime one can simply use get requests instead in some cases. 

## Steps to Reproduce (for bugs)
1. Download & Run the provided zip file (code reproduced in MCVE section for ease of reading)
1. Load localhost:8192/status to see what it looks like when you're not signed in
2. Load localhost:8192/signin in a web browser, as a GET request
3. Load localhost:8192/status in a web browser to show that you're signed in as "some user"
4. Load localhost:8192/signout **AS A POST REQUEST** (use the browser's development tools to make it POST as no UI is provided for this), and supposedly sign out
5. Load localhost:8192/status to see that you're still signed in.

# MCVE
Download buildable project (with Cargo.toml, etc.): [mcve.zip](https://github.com/actix/actix-web/files/5999992/mcve.zip)
```rust
use actix_web::{App, get, post, HttpServer, HttpResponse};
use actix_session::{CookieSession, Session};

#[get("/signin")] //GET for ease of testing so I don't need to make a frontend for a simple exampl
async fn signin(session: Session) -> String{
    session.set("username", "some user").expect("Failed to set username");
    "Success!".into()
}

#[post("/signout")] //use browser's development tools to make a POST request
async fn signout(session: Session) -> HttpResponse{
    session.purge();
    HttpResponse::Ok().body("Signed out")
}

#[get("/status")] //GET for ease of testing so I don't need to make a frontend for a simple exampl
async fn status(session: Session) -> String{
    session.get("username").expect("Failed to read session").unwrap_or("Not signed in".into())
}

#[actix_web::main]
async fn main() -> actix_web::Result<()>{
    HttpServer::new(||
        App::new()
            .wrap(
                CookieSession::signed(&[0; 32]) //of course, in my real code I have a proper key
                    .path("/")
                    .lazy(true)
                    .secure(false),
            )
            .service(signin)
            .service(signout)
            .service(status)
    )
    .bind("localhost:8192")?
    .run()
    .await?;

    Ok(())
}
```

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.50.0 (cb75ad5db 2021-02-10)
* Actix Web Version: 3.3.2, session is 0.4.0

**Comment by realaravinth** [comment] 2021-08-04 06:57
I'm unable to reproduce this bug with the MVCE you provided on Firefox. Are you still facing this issue? If yes, please share request, response and any console errors associated with the request to `/signout`.

On my end, `/signout/` responds with a `set-cookie` header with empty value, max-age set to 0 and expiry set to current date and time. This is the expected behavior and it works.

- Request headers:
```
POST /signout HTTP/1.1
Host: localhost:8192
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Origin: http://localhost:8192
Cookie: actix-session=0KS+GQMeGSzmdEf9YoCPo%2FMkykNUEP3v09R0Ek6Gfr0%3D%7B%22username%22%3A%22%5C%22some%20user%5C%22%22%7D
---snip---
```
- Response headers:
```
HTTP/1.1 200 OK
content-length: 10
set-cookie: actix-session=; Max-Age=0; Expires=Tue, 04 Aug 2020 06:36:34 GMT
date: Wed, 04 Aug 2021 06:36:34 GMT
```
---
Is there any reason why you are using `actix-session` over `actix-identity` for cookie auth? IMO, for cookie auth, `actix-identity` has a much nicer API.

```rust
#[get("/signin")] 
async fn signin(session: Session) -> String{
    session.set("username", "some user").expect("Failed to set username");
    "Success!".into()
}

#[post("/signout")]
async fn signout(session: Session) -> HttpResponse{
    session.purge();
    HttpResponse::Ok().body("Signed out")
}

#[get("/status")]
async fn status(session: Session) -> String{
    session.get("username").expect("Failed to read session").unwrap_or("Not signed in".into())
}
```
with `actix-identity` would become

```rust
#[get("/signin")] 
async fn signin(id: Identity) -> String{
    id.remember("user");
    "Success!".into()
}

#[post("/signout")] 
async fn signout(id: Identity) -> HttpResponse{
    id.forget();
    HttpResponse::Ok().body("Signed out")
}

#[get("/status")]
async fn status(session: Session) -> String{
   id.identity().unwrap_or("Not signed in".into())
}
```

**Comment by LukeMathWalker** [comment] 2022-03-16 12:58
This should no longer be an issue - `0.6.0` distinguishes between a session that was never used and pre-existing session that became empty, so the purge logic is never skipped for the latter (see https://github.com/actix/actix-extras/blob/2417549b356ddb4377845b7b88f40128e68a51fb/actix-session/src/middleware.rs#L425 )
We can close this @robjtede.

**Closed** 2022-03-16 13:01 UTC
Labels: C-bug, A-session
