### ISSUE TITLE
actix-web-httpauth middleware extractors are not compatible with actix 4

### ISSUE THREAD

**Issue by jbtrystram** [actix/actix-extras#160] opened 2021-03-01 13:58 UTC
## Expected Behavior
Here is how i defined my http basic auth validator : 
```
 let auth = HttpAuthentication::bearer(|req, auth| {
            let token = auth.token().to_string();

            async {
                let authenticator = req.app_data::<web::Data<Authenticator>>();
                log::info!("Authenticator: {:?}", &authenticator);
                let authenticator = authenticator.ok_or_else(|| ServiceError::InternalError {
                    message: "Missing authenticator instance".into(),
                })?;

                match authenticator.validate_token(token).await {
                    Ok(_) => Ok(req),
                    Err(AuthenticatorError::Missing) => Err(ServiceError::InternalError {
                        message: "Missing authenticator".into(),
                    }
                    .into()),
                    Err(AuthenticatorError::Failed) => {
                        Err(ServiceError::AuthenticationError.into())
                    }
                }
            }
        });
```
Here `Authenticator` is an openID client. It works well with actix 3.

## Current Behavior
When switching to actix 4 i get a compilation error for a missing trait implementation : 
```
the trait Transform<actix_web::scope::ScopeService, ServiceRequest> is not implemented for HttpAuthentication<BearerAuth, [closure@/drogue-cloud/authentication-service/src/lib.rs:27:52: 48:10]>
```

## Possible Solution
I suppose `HttpAuthentication::bearer` needs to implement the proper traits to be accepted as a valid middleware by `App::new().wrap()`

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.49.0 (e1884a8e3 2020-12-29)
* Actix-* crate(s) Version:
actix-web-httpauth = "0.5"
actix-web = "4.0.0-beta.3"
actix = "0.10"
actix-cors = "0.5"

**Comment by robjtede** [comment] 2021-03-01 13:59
duplicate of #146

**Comment by jbtrystram** [comment] 2021-03-01 14:00
@robjtede ah I see there is work already done, awesome ! Sorry for the duplicate.

**Closed by robjtede** 2021-03-01 13:59 UTC
