### ISSUE TITLE
session and identity crates fail to compile on latest versions

### ISSUE THREAD

**Issue by akrantz01** [actix/actix-extras#182] opened 2021-04-28 20:27 UTC
## Expected Behavior

Both packages should compile without issue.

## Current Behavior

Compiling either one results in at least 5 errors with cookies and serializing to JSON.
[`cargo build` output for both packages](https://gist.github.com/akrantz01/9485e571211dd8b7b3084206a02d4797)

## Steps to Reproduce (for bugs)

1. Clone the repository
2. Checkout either the latest session or identity build
3. Run cargo build for the respective package

## Context

I'm building a web app using actix-web and I need a way to handle authentication with cookies.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.51.0
* Actix-* crate(s) Version: actix-session: 0.5.0-beta.1, actix-identity: 0.4.0-beta.1

**Comment by robjtede** [comment] 2021-04-29 08:45
duplicate of #176

**Closed** 2021-06-27 06:02 UTC
Labels: duplicate
